export const allSuggestions = [
  {
    name: 'Monkey D Luffy',
    alias: 'Luffy',
    anime: 'One Piece',
    type: 'character',
  },
  { name: 'Nami', anime: 'One Piece', type: 'character' },
  { name: 'Nico Robin', alias: 'Robin', anime: 'One Piece', type: 'character' },
  {
    name: 'Boa Hancock',
    alias: 'Hancock',
    anime: 'One Piece',
    type: 'character',
  },
  {
    name: 'Vinsmoke Sanji',
    alias: 'Sanji',
    anime: 'One Piece',
    type: 'character',
  },
  {
    name: 'Tony Tony Chopper',
    alias: 'Chopper',
    anime: 'One Piece',
    type: 'character',
  },
  {
    name: 'Roronoa Zoro',
    alias: 'Zoro',
    anime: 'One Piece',
    type: 'character',
  },
  { name: 'usopp', anime: 'One Piece', type: 'character' },

  { name: 'Fairy Tail', type: 'anime' },
  {
    name: 'Natsu Dragneel',
    anime: 'Fairy Tail',
    type: 'character',
  },
  {
    name: 'Lucy Heartfilia',
    anime: 'Fairy Tail',
    type: 'character',
  },
  { name: 'Erza Scarlet', anime: 'Fairy Tail', type: 'character' },
  { name: 'Wendy Marvell', anime: 'Fairy Tail', type: 'character' },
  { name: 'Gray Fullbuster', anime: 'Fairy Tail', type: 'character' },
  { name: 'Juvia Lockser', anime: 'Fairy Tail', type: 'character' },

  { name: 'Naruto', type: 'anime' },
  {
    name: 'Uzumaki Naruto',
    alias: 'naruto',
    anime: 'Naruto',
    type: 'character',
  },
  {
    name: 'Uchiha Sasuke ',
    alias: 'Sasuke',
    anime: 'Naruto',
    type: 'character',
  },
  {
    name: 'Haruno Sakura',
    alias: 'Sakura',
    anime: 'Naruto',
    type: 'character',
  },
  {
    name: 'Hyuuga Hinata',
    alias: 'Hinata',
    anime: 'Naruto',
    type: 'character',
  },
  { name: 'Yamanaka Ino', alias: 'Ino', anime: 'Naruto', type: 'character' },
  { name: 'Tsunade', anime: 'Naruto', type: 'character' },
  {
    name: 'Hatake Kakashi',
    alias: 'Kakashi',
    anime: 'Naruto',
    type: 'character',
  },
  {
    name: 'Uchiha Itachi',
    alias: 'Itachi',
    anime: 'Naruto',
    type: 'character',
  },
  { name: 'Bleach', type: 'anime' },
  { name: 'Boku no Hero Academia', type: 'anime' },
  { name: 'Jujutsu Kaisen', type: 'anime' },
  { name: 'Chainsaw Man', type: 'anime' },
  { name: 'To Love Ru', alias: 'Love', type: 'anime' },
  { name: 'Spy x Family', alias: 'Family', type: 'anime' },
  {
    name: '5-toubun no Hanayome',
    alias: 'Gotoubun no Hanayome',
    type: 'anime',
  },
  { name: 'Blue Archive', type: 'anime' },
  { name: 'Genshin Impact', alias: 'Impact', type: 'anime' },
  { name: 'honkai:_star_rail', type: 'anime' },
  { name: 'Zenless Zone Zero', alias: "zzz", type: 'anime' },
  { name: 'hololive', type: 'anime' },
];