export const allSuggestions = [
  { name: 'One Piece', type: 'anime' },
  {
    name: 'Monkey D Luffy',
    alias: 'Luffy',
    anime: 'One Piece',
    type: 'character',
  },
  { name: 'Nami', anime: 'One Piece', type: 'character' },
  { name: 'Nico Robin', alias: 'Robin', anime: 'One Piece', type: 'character' },
  {
    name: 'Boa Hancock',
    alias: 'Hancock',
    anime: 'One Piece',
    type: 'character',
  },
  {
    name: 'Vinsmoke Sanji',
    alias: 'Sanji',
    anime: 'One Piece',
    type: 'character',
  },
  {
    name: 'Tony Tony Chopper',
    alias: 'Chopper',
    anime: 'One Piece',
    type: 'character',
  },
  {
    name: 'Roronoa Zoro',
    alias: 'Zoro',
    anime: 'One Piece',
    type: 'character',
  },
  { name: 'usopp', anime: 'One Piece', type: 'character' },

  { name: 'Fairy Tail', type: 'anime' },
  {
    name: 'Natsu Dragneel',
    anime: 'Fairy Tail',
    type: 'character',
  },
  {
    name: 'Lucy Heartfilia',
    anime: 'Fairy Tail',
    type: 'character',
  },
  { name: 'Erza Scarlet', anime: 'Fairy Tail', type: 'character' },
  { name: 'Wendy Marvell', anime: 'Fairy Tail', type: 'character' },
  { name: 'Gray Fullbuster', anime: 'Fairy Tail', type: 'character' },
  { name: 'Juvia Lockser', anime: 'Fairy Tail', type: 'character' },

  { name: 'Naruto', type: 'anime' },
  {
    name: 'Uzumaki Naruto',
    alias: 'naruto',
    anime: 'Naruto',
    type: 'character',
  },
  {
    name: 'Uchiha Sasuke ',
    alias: 'Sasuke',
    anime: 'Naruto',
    type: 'character',
  },
  {
    name: 'Haruno Sakura',
    alias: 'Sakura',
    anime: 'Naruto',
    type: 'character',
  },
  {
    name: 'Hyuuga Hinata',
    alias: 'Hinata',
    anime: 'Naruto',
    type: 'character',
  },
  { name: 'Yamanaka Ino', alias: 'Ino', anime: 'Naruto', type: 'character' },
  { name: 'Tsunade', anime: 'Naruto', type: 'character' },
  {
    name: 'Hatake Kakashi',
    alias: 'Kakashi',
    anime: 'Naruto',
    type: 'character',
  },
  {
    name: 'Uchiha Itachi',
    alias: 'Itachi',
    anime: 'Naruto',
    type: 'character',
  },
  { name: 'Dragon Ball', alias: 'DB', type: 'anime' },
  { name: 'Dragon Ball Z', alias: 'DBZ', type: 'anime' },
  { name: 'Son Goku', alias: 'Goku', anime: 'Dragon Ball', type: 'character' },
  { name: 'Android 18', alias: '18', anime: 'Dragon Ball', type: 'character' },
  { name: 'Bulma', anime: 'Dragon Ball', type: 'character' },
  { name: 'Vegeta', anime: 'Dragon Ball', type: 'character' },
  { name: 'Bleach', type: 'anime' },
  {
    name: 'Kurosaki Ichigo',
    alias: 'Ichigo',
    anime: 'Bleach',
    type: 'character',
  },
  { name: 'Kuchiki Rukia', alias: 'Rukia', anime: 'Bleach', type: 'character' },
  {
    name: 'Shihouin Yoruichi',
    alias: 'Yoruichi',
    anime: 'Bleach',
    type: 'character',
  },
  {
    name: 'Inoue Orihime',
    alias: 'Orihime',
    anime: 'Bleach',
    type: 'character',
  },
  {
    name: 'Matsumoto Rangiku',
    alias: 'Rangiku',
    anime: 'Bleach',
    type: 'character',
  },
  { name: 'Boku no Hero Academia', alias: 'My Hero Academia', type: 'anime' },
  {
    name: 'Bakugou Katsuki',
    anime: 'Boku no Hero',
    type: 'character',
  },
  {
    name: 'Midoriya Izuku ',
    alias: 'Deku',
    anime: 'Boku no Hero',
    type: 'character',
  },
  {
    name: 'Todoroki Shouto',
    alias: 'Shouto',
    anime: 'Boku no Hero',
    type: 'character',
  },
  {
    name: 'Uraraka Ochako',
    alias: 'Uravity',
    anime: 'Boku no Hero',
    type: 'character',
  },
  {
    name: 'Asui Tsuyu',
    alias: 'Tsuyu',
    anime: 'Boku no Hero',
    type: 'character',
  },
  {
    name: 'Yaoyorozu Momo',
    alias: 'Momo',
    anime: 'Boku no Hero',
    type: 'character',
  },
  {
    name: 'Toga Himiko',
    alias: 'Himiko',
    anime: 'Boku no Hero',
    type: 'character',
  },

  { name: 'Hatsune Miku', alias: 'Miku', type: 'character' },

  { name: 'Sousou no Frieren', alias: 'Frieren', type: 'anime' },
  { name: 'Frieren', anime: 'Sousou no Frieren', type: 'character' },
  { name: 'Fern', anime: 'Sousou no Frieren', type: 'character' },

  { name: 'Gintama', type: 'anime' },
  {
    name: 'Kaguya-sama wa Kokurasetai ~tensai-tachi no Renai >unousen~',
    alias: 'Love is War',
    type: 'anime',
  },
  { name: 'Neon Genesis Evangelion', alias: 'Evangelion', type: 'anime' },
  { name: 'Darling in the Franxx', alias: 'Evangelion', type: 'anime' },
  { name: 'Sword Art Online', alias: 'SAO', type: 'anime' },
  { name: 'Kirito', anime: 'Sword Art Online', type: 'character' },

  { name: 'Jujutsu Kaisen', type: 'anime' },
  { name: 'Chainsaw Man', type: 'anime' },
  { name: 'To Love Ru', alias: 'Love', type: 'anime' },
  { name: 'Spy x Family', alias: 'Family', type: 'anime' },
  { name: 'Highschool DxD', alias: 'dxd', type: 'anime' },
  {
    name: '5-toubun no Hanayome',
    alias: 'Gotoubun no Hanayome',
    type: 'anime',
  },
  { name: 'Blue Archive', alias: 'ba', type: 'anime' },
  { name: 'Genshin Impact', alias: 'Impact', type: 'anime' },
  { name: 'honkai: Star Rail', alias: 'Star Rail', type: 'anime' },
  { name: 'Zenless Zone Zero', alias: 'zzz', type: 'anime' },
  { name: 'hololive', type: 'anime' },
];